name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: docker.burek.it
        username: ${{ secrets.BUREK_DOCKER_USERNAME }}
        password: ${{ secrets.BUREK_DOCKER_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: docker.burek.it/scrapple-frontend:latest
