name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    branches: [ master ]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get artifacts
      uses: actions/download-artifact@v2
      with:
        name: build
    - name: Deploy to server
      uses: easingthemes/ssh-deploy@v2.0.7
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        REMOTE_HOST: "scrapple.burek.it"
        REMOTE_USER: "scrapple"
        TARGET: "scrapple-fe"
        ARGS: "-rltgoDzvO"
        SOURCE: "dist/"
