name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Cache
      uses: actions/cache@v2.1.1
      with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/package-lock.json') }}
    - run: npm ci
    - run: npm run build --if-present
